version: '3.9'
services:
  cypress:
    image: cypress/included:latest
    command: ${CMD}
    volumes:
      - "./:/source"
    working_dir: /source
    environment:
      DOMAIN_SUFFIX: ${DOMAIN_SUFFIX}
    dns:
    - ${DNS1}
    - ${DNS2}