name: CI

on:
  push:

jobs:
  e2e-local-lab:
    uses: ./.github/workflows/run-e2e.yml
    with:
      client: local
      environment: lab
      gitref: ${{ github.ref }}
    secrets:
      sops_age_key: ${{ secrets.SOPS_AGE_PRIVATE_KEY }}

  e2e-remote-lab:
    uses: ./.github/workflows/run-e2e.yml
    with:
      client: remote
      environment: lab
      gitref: ${{ github.ref }}
    secrets:
      sops_age_key: ${{ secrets.SOPS_AGE_PRIVATE_KEY }}
