on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    
# TODO: Set token perms

jobs:
  e2e-tests:
    runs-on: [ self-hosted ]
    services:
      webdriver-chrome:
        image: selenium/standalone-chrome
        ports:
          - 4444
    steps:
      - name: Test node
        run: echo ${{ job.services.webdriver-chrome.ports[4444] }}

      - name: Check out e2e repository
        uses: actions/checkout@v3.5.2
        with:
          repository: homecentr/e2e
          ref: refs/heads/master
          path: e2e

      - name: Install dependencies
        run: cd e2e && yarn

      - name: Ping webdriver
        run: ping webdriver-chrome

      # TODO: Start a chrome driver container
      # TODO: Run E2E
      # TODO: Kill the chrome driver container (runs always !!!)