on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      gitref:
        required: false
        type: string
        default: master
    secrets:
      sops_age_key:
        required: true

jobs:
  e2e-preparations:
    runs-on: [ self-hosted ]
    outputs:
      dns1: ${{ steps.vars.outputs.DNS1 }}
      dns2: ${{ steps.vars.outputs.DNS2 }}
    steps:
      - name: Check out e2e repository
        uses: actions/checkout@v3.5.2
        with:
          repository: homecentr/e2e
          ref: refs/heads/${{ inputs.gitref }}
          path: e2e

      - name: Load variables
        id: vars
        run: cat ./e2e/environments/remote.env >> "$GITHUB_OUTPUT"

  e2e-tests-local:
    runs-on: [ self-hosted ]
    needs: [ e2e-preparations ]
    services:
      webdriver-chrome:
        image: selenium/standalone-chrome
        ports:
          - 4444
          - 7900
        env:
          VNC_NO_PASSWORD: 1
        options: --shm-size=2g --dns=${{ needs.e2e-preparations.outputs.dns1 }} --dns=${{ needs.e2e-preparations.outputs.dns2 }}
    steps:
      - name: Print debug link
        run: echo "::info::http://$HOST_IP:${{ job.services.webdriver-chrome.ports[7900] }}"

      - name: Check out e2e repository
        uses: actions/checkout@v3.5.2
        with:
          repository: homecentr/e2e
          ref: refs/heads/${{ inputs.gitref }}
          path: e2e

      - name: Install dependencies
        run: cd e2e && yarn

      - name: Run tests
        run: cd e2e && yarn test:remote:${{ inputs.environment }}
        env:
          WEBDRIVER_HOST: host.docker.internal
          WEBDRIVER_PORT: ${{ job.services.webdriver-chrome.ports[4444] }}
          SOPS_AGE_KEY: ${{ secrets.sops_age_key }}
          SCREENSHOTS_ENABLED: "false"
