on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      branch:
        required: false
        type: string
        default: feat/v1 # TODO: Change to master
    secrets:
      sops_age_key:
        required: true
    
# TODO: Set token perms

jobs:
  load-config:
    runs-on: [ self-hosted ]
    outputs:
      DNS1: ${{ steps.vars.outputs.DNS1 }}
      DNS2: ${{ steps.vars.outputs.DNS2 }}
    steps:
      - name: Check out e2e repository
        uses: actions/checkout@v3.5.2
        with:
          repository: homecentr/e2e
          ref: refs/heads/${{ inputs.branch }}
          path: e2e

      - name: Load variables
        id: vars
        run: cat ./e2e/environments/local.${{ inputs.environment }}.env >> "$GITHUB_OUTPUT"

  e2e-tests-local:
    runs-on: [ self-hosted ]
    needs: [ load-config ]
    services:
      webdriver-chrome:
        image: selenium/standalone-chrome
        ports:
          - 4444
          - 7900
        options: --dns=${{ needs.load-config.outputs.DNS1 }} --dns=${{ needs.load-config.outputs.DNS2 }}
    steps:
      - name: Check out e2e repository
        uses: actions/checkout@v3.5.2
        with:
          repository: homecentr/e2e
          ref: refs/heads/${{ inputs.branch }}
          path: e2e

      - name: Install dependencies
        run: cd e2e && yarn

      - name: Wait
        run: sleep 60

      - name: Run tests
        run: cd e2e && yarn test:local:${{ inputs.environment }}
        env:
          WEBDRIVER_HOST: host.docker.internal
          WEBDRIVER_PORT: ${{ job.services.webdriver-chrome.ports[4444] }}
          SOPS_AGE_KEY: ${{ secrets.sops_age_key }}
          SCREENSHOTS_ENABLED: "false"

  # TODO: Run remote tests