on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      branch:
        required: false
        type: string
        default: feat/v1 # TODO: Change to master
    
# TODO: Set token perms

jobs:
  load-config:
    runs-on: [ self-hosted ]
    steps:
      - name: Check out e2e repository
        uses: actions/checkout@v3.5.2
        with:
          repository: homecentr/e2e
          ref: refs/heads/${{ inputs.branch }}
          path: e2e

      - name: Load variables
        id: vars
        run: cat ./e2e/environments/local.${{ inputs.environment }}.env >> "$GITHUB_OUTPUT"

  e2e-tests:
    runs-on: [ self-hosted ]
    needs: [ load-config ]
    services:
      webdriver-chrome:
        image: selenium/standalone-chrome # TODO: We need to configure the DNS !!!
        ports:
          - 4444
        # options: --dns ${{ steps.primary_dns. }}
        # options: DNS HOW
    steps:
      - name: Debug 1
        run: echo ${{ steps.vars.outputs.DNS1 }}

      - name: Debug 2
        run: echo ${{ steps.vars.outputs.DNS2 }}

      - name: Check out e2e repository
        uses: actions/checkout@v3.5.2
        with:
          repository: homecentr/e2e
          ref: refs/heads/${{ inputs.branch }}
          path: e2e

      - name: Install dependencies
        run: cd e2e && yarn

      - name: Run tests
        run: cd e2e && yarn test:${{ inputs.environment }}
        env:
          WEBDRIVER_HOST: host.docker.internal
          WEBDRIVER_PORT: ${{ job.services.webdriver-chrome.ports[4444] }}


      # TODO: Run E2E
      # TODO: Kill the chrome driver container (runs always !!!)